tunning:
  alpha: 1
  beta: 1
simulated_annealing:
  max_init_tries: 5000
  max_iterations: 3000
  timeout: 3600
  stagnation_limit: 200 # Iterations without improvement
  max_neighbor_tries: 30 # Number of neighbor solutions to try at each temperature
  initial_temperature: 150.0
  cooling_rate: 0.995
  min_temperature: 1.0e-3
  refinement_priority_method: NORMAL # NORMAL or PSO
  refinement_iterations: 50
  refinement_sigma_max: 0.1
  refinement_sigma_min: 1.0e-3
  refinement_pso_warm_size: 30
  refinement_pso_velocity_clamp: 2
  refinement_pso_inertia_weight: 0.5
  refinement_pso_cognitive_coef: 1.5
  refinement_pso_social_coef: 1.5

random_search:
  max_iterations: 1000
  timeout: 3600
  stagnation_limit: 200
  break_on_first_feasible: false

genetic_algorithm:
  population_size: 150
  max_generations: 800
  timeout: 3600
  elite_count: 5
  stagnation_limit: 200
  mutation_rate: 0.15
  crossover_rate: 0.75